name: Realtime Allure Report

on: 
  push:
    branch: 
      "realtime"

jobs:
  build-allure-report-v1:
    runs-on: ubuntu-latest
    services:
      nginx:
        image: nginx
        ports:
          - 8080:8080
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: | 
          curl https://loca.lt/mytunnelpassword
          npm install -g localtunnel
          lt --port 8080 &
          sleep 1m
